version: "3.9"
services:
  db:
    image: "postgres:17"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"
      ]
      start_period: 30s
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    build: .
    env_file: docker.env
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DB_NAME: ${DATABASE_NAME}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      TIME_ZONE: ${TIME_ZONE}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"