# Generated by Django 5.1 on 2024-08-31 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 16, 23, 52, 26272, tzinfo=datetime.timezone.utc)),
        ),
    ]
