# Generated by Django 5.1 on 2024-08-31 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 31, 16, 27, 25, 712693, tzinfo=datetime.timezone.utc)),
        ),
    ]
